name: Serious-mental-illness-requires-treatment
favicon: null
layout_spectrum: 0.74642
typography_spectrum: 0.82974
title: "Rights for people, not diseases. Don't let psychosis make the decisions! "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a000a'
    - '#ffffff'
    - '#f02e28'
    - '#646064'
    - '#ada9ad'
  brandStrength: 0.5625
  lightness: 0.01576943788677454
  saturation: 0.4449057341553271
  rhythmicContrast: 0.07294020312838256
purpose: []
